// @generated by scripts/generate-integrated-runtime-domain-schema.mjs
// Source: engine/schema/integrated-runtime-r5-r9.v1.json
// Do not edit by hand.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct IntegratedRuntimeDomainWireFamilyV1 {
    pub phase: &'static str,
    pub domain: &'static str,
    pub id: &'static str,
    pub direction: &'static str,
    pub magic: [u8; 4],
    pub type_id: &'static str,
    pub operation_schema: u16,
    pub inner_schema: u16,
    pub normal_path: bool,
}

pub const INTEGRATED_RUNTIME_DOMAIN_SCHEMA_FINGERPRINT_V1: &str =
    "f5fb5cab925d60512fb52436b26ef3f166f9865f84f8ee7bf43d3c7cd21ac177";
pub const INTEGRATED_RUNTIME_DOMAIN_WIRE_VERSION_V1: u16 = 1;
pub const INTEGRATED_RUNTIME_SCHEMA_VERSION_V1: u16 = 6;

pub const CONTEXT_COMMAND_CONTINUITY_V2_MAGIC: [u8; 4] = *b"BWS6";
pub const CONTEXT_COMMAND_CONTINUITY_V2_TYPE_ID: &str = "blockwild.simulation.context-command-continuity.r5.v2";
pub const CONTEXT_COMMAND_CONTINUITY_V2_OPERATION_SCHEMA: u16 = 2;
pub const CONTEXT_COMMAND_CONTINUITY_V2_INNER_SCHEMA: u16 = 2;

pub const PLAYER_BOOTSTRAP_STATUS_V1_MAGIC: [u8; 4] = *b"BWS5";
pub const PLAYER_BOOTSTRAP_STATUS_V1_TYPE_ID: &str = "blockwild.simulation.player-bootstrap-status.r5.v1";
pub const PLAYER_BOOTSTRAP_STATUS_V1_OPERATION_SCHEMA: u16 = 1;
pub const PLAYER_BOOTSTRAP_STATUS_V1_INNER_SCHEMA: u16 = 1;

pub const PLAYER_COMBAT_BOOTSTRAP_STATUS_V1_MAGIC: [u8; 4] = *b"BWS7";
pub const PLAYER_COMBAT_BOOTSTRAP_STATUS_V1_TYPE_ID: &str = "blockwild.simulation.player-combat-bootstrap-status.r7.v1";
pub const PLAYER_COMBAT_BOOTSTRAP_STATUS_V1_OPERATION_SCHEMA: u16 = 1;
pub const PLAYER_COMBAT_BOOTSTRAP_STATUS_V1_INNER_SCHEMA: u16 = 1;

pub const PLAYER_GAME_MODE_SET_V1_MAGIC: [u8; 4] = *b"BWM7";
pub const PLAYER_GAME_MODE_SET_V1_TYPE_ID: &str = "blockwild.simulation.player-game-mode-set.r5.v1";
pub const PLAYER_GAME_MODE_SET_V1_OPERATION_SCHEMA: u16 = 1;
pub const PLAYER_GAME_MODE_SET_V1_INNER_SCHEMA: u16 = 1;

pub const PLAYER_RESPAWN_V1_MAGIC: [u8; 4] = *b"BWD7";
pub const PLAYER_RESPAWN_V1_TYPE_ID: &str = "blockwild.simulation.player-respawn.r5-r6-r7.v1";
pub const PLAYER_RESPAWN_V1_OPERATION_SCHEMA: u16 = 1;
pub const PLAYER_RESPAWN_V1_INNER_SCHEMA: u16 = 1;

pub const SIMULATION_CAMERA_CONFIG_V1_MAGIC: [u8; 4] = *b"BWC5";
pub const SIMULATION_CAMERA_CONFIG_V1_TYPE_ID: &str = "blockwild.simulation.camera-config.r5.v1";
pub const SIMULATION_CAMERA_CONFIG_V1_OPERATION_SCHEMA: u16 = 1;
pub const SIMULATION_CAMERA_CONFIG_V1_INNER_SCHEMA: u16 = 1;

pub const SIMULATION_PLAYER_BIND_V2_MAGIC: [u8; 4] = *b"BWB6";
pub const SIMULATION_PLAYER_BIND_V2_TYPE_ID: &str = "blockwild.simulation.player-bind.r5.v2";
pub const SIMULATION_PLAYER_BIND_V2_OPERATION_SCHEMA: u16 = 2;
pub const SIMULATION_PLAYER_BIND_V2_INNER_SCHEMA: u16 = 1;

pub const SIMULATION_PLAYER_BIND_V3_MAGIC: [u8; 4] = *b"BWB6";
pub const SIMULATION_PLAYER_BIND_V3_TYPE_ID: &str = "blockwild.simulation.player-bind.r5.v3";
pub const SIMULATION_PLAYER_BIND_V3_OPERATION_SCHEMA: u16 = 3;
pub const SIMULATION_PLAYER_BIND_V3_INNER_SCHEMA: u16 = 1;

pub const SIMULATION_PLAYER_BIND_V4_MAGIC: [u8; 4] = *b"BWB6";
pub const SIMULATION_PLAYER_BIND_V4_TYPE_ID: &str = "blockwild.simulation.player-bind.r5.v4";
pub const SIMULATION_PLAYER_BIND_V4_OPERATION_SCHEMA: u16 = 4;
pub const SIMULATION_PLAYER_BIND_V4_INNER_SCHEMA: u16 = 1;

pub const CONTEXT_COMMAND_CONTINUITY_RECEIPT_V2_MAGIC: [u8; 4] = *b"BWO6";
pub const CONTEXT_COMMAND_CONTINUITY_RECEIPT_V2_TYPE_ID: &str =
    "blockwild.simulation.context-command-continuity-receipt.r5.v2";
pub const CONTEXT_COMMAND_CONTINUITY_RECEIPT_V2_OPERATION_SCHEMA: u16 = 2;
pub const CONTEXT_COMMAND_CONTINUITY_RECEIPT_V2_INNER_SCHEMA: u16 = 2;

pub const PLAYER_BOOTSTRAP_STATUS_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWO5";
pub const PLAYER_BOOTSTRAP_STATUS_RECEIPT_V1_TYPE_ID: &str =
    "blockwild.simulation.player-bootstrap-status-receipt.r5.v1";
pub const PLAYER_BOOTSTRAP_STATUS_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const PLAYER_BOOTSTRAP_STATUS_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const PLAYER_COMBAT_BOOTSTRAP_STATUS_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWO7";
pub const PLAYER_COMBAT_BOOTSTRAP_STATUS_RECEIPT_V1_TYPE_ID: &str =
    "blockwild.simulation.player-combat-bootstrap-status-receipt.r7.v1";
pub const PLAYER_COMBAT_BOOTSTRAP_STATUS_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const PLAYER_COMBAT_BOOTSTRAP_STATUS_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const PLAYER_GAME_MODE_SET_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWN7";
pub const PLAYER_GAME_MODE_SET_RECEIPT_V1_TYPE_ID: &str = "blockwild.simulation.player-game-mode-set-receipt.r5.v1";
pub const PLAYER_GAME_MODE_SET_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const PLAYER_GAME_MODE_SET_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const PLAYER_RESPAWN_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWE7";
pub const PLAYER_RESPAWN_RECEIPT_V1_TYPE_ID: &str = "blockwild.simulation.player-respawn-receipt.r5-r6-r7.v1";
pub const PLAYER_RESPAWN_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const PLAYER_RESPAWN_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const SIMULATION_CAMERA_CONFIG_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWR5";
pub const SIMULATION_CAMERA_CONFIG_RECEIPT_V1_TYPE_ID: &str = "blockwild.simulation.camera-config-receipt.r5.v1";
pub const SIMULATION_CAMERA_CONFIG_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const SIMULATION_CAMERA_CONFIG_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const SIMULATION_PLAYER_BIND_RECEIPT_V2_MAGIC: [u8; 4] = *b"BWB6";
pub const SIMULATION_PLAYER_BIND_RECEIPT_V2_TYPE_ID: &str = "blockwild.simulation.player-bind-receipt.r5.v2";
pub const SIMULATION_PLAYER_BIND_RECEIPT_V2_OPERATION_SCHEMA: u16 = 2;
pub const SIMULATION_PLAYER_BIND_RECEIPT_V2_INNER_SCHEMA: u16 = 1;

pub const SIMULATION_PLAYER_BIND_FINAL_RECEIPT_V3_MAGIC: [u8; 4] = *b"BWF6";
pub const SIMULATION_PLAYER_BIND_FINAL_RECEIPT_V3_TYPE_ID: &str =
    "blockwild.simulation.player-bind-final-receipt.r5.v3";
pub const SIMULATION_PLAYER_BIND_FINAL_RECEIPT_V3_OPERATION_SCHEMA: u16 = 3;
pub const SIMULATION_PLAYER_BIND_FINAL_RECEIPT_V3_INNER_SCHEMA: u16 = 1;

pub const SIMULATION_PLAYER_BIND_FINAL_RECEIPT_V4_MAGIC: [u8; 4] = *b"BWF7";
pub const SIMULATION_PLAYER_BIND_FINAL_RECEIPT_V4_TYPE_ID: &str =
    "blockwild.simulation.player-bind-final-receipt.r5.v4";
pub const SIMULATION_PLAYER_BIND_FINAL_RECEIPT_V4_OPERATION_SCHEMA: u16 = 4;
pub const SIMULATION_PLAYER_BIND_FINAL_RECEIPT_V4_INNER_SCHEMA: u16 = 1;

pub const ENTITY_AUTHORITY_EXPORT_V1_MAGIC: [u8; 4] = *b"BWQ6";
pub const ENTITY_AUTHORITY_EXPORT_V1_TYPE_ID: &str = "blockwild.entities.authority-export.r6.v1";
pub const ENTITY_AUTHORITY_EXPORT_V1_OPERATION_SCHEMA: u16 = 1;
pub const ENTITY_AUTHORITY_EXPORT_V1_INNER_SCHEMA: u16 = 1;

pub const ENTITY_AUTHORITY_IMPORT_V2_MAGIC: [u8; 4] = *b"BWI6";
pub const ENTITY_AUTHORITY_IMPORT_V2_TYPE_ID: &str = "blockwild.entities.authority-import.r6.v2";
pub const ENTITY_AUTHORITY_IMPORT_V2_OPERATION_SCHEMA: u16 = 1;
pub const ENTITY_AUTHORITY_IMPORT_V2_INNER_SCHEMA: u16 = 1;

pub const ENTITY_COMPATIBILITY_EXPORT_V1_MAGIC: [u8; 4] = *b"BWQ5";
pub const ENTITY_COMPATIBILITY_EXPORT_V1_TYPE_ID: &str = "blockwild.entities.compatibility-export.r6.v1";
pub const ENTITY_COMPATIBILITY_EXPORT_V1_OPERATION_SCHEMA: u16 = 1;
pub const ENTITY_COMPATIBILITY_EXPORT_V1_INNER_SCHEMA: u16 = 1;

pub const ENTITY_COMPATIBILITY_IMPORT_V1_MAGIC: [u8; 4] = *b"BWI5";
pub const ENTITY_COMPATIBILITY_IMPORT_V1_TYPE_ID: &str = "blockwild.entities.compatibility-import.r6.v1";
pub const ENTITY_COMPATIBILITY_IMPORT_V1_OPERATION_SCHEMA: u16 = 1;
pub const ENTITY_COMPATIBILITY_IMPORT_V1_INNER_SCHEMA: u16 = 1;

pub const ENTITY_COMMAND_V1_MAGIC: [u8; 4] = *b"BWE6";
pub const ENTITY_COMMAND_V1_TYPE_ID: &str = "blockwild.entities.command-batch.r6.v1";
pub const ENTITY_COMMAND_V1_OPERATION_SCHEMA: u16 = 1;
pub const ENTITY_COMMAND_V1_INNER_SCHEMA: u16 = 1;

pub const ENTITY_AUTHORITY_IMPORT_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWU6";
pub const ENTITY_AUTHORITY_IMPORT_RECEIPT_V1_TYPE_ID: &str = "blockwild.entities.authority-import-receipt.r6.v1";
pub const ENTITY_AUTHORITY_IMPORT_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const ENTITY_AUTHORITY_IMPORT_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const ENTITY_AUTHORITY_SNAPSHOT_V2_MAGIC: [u8; 4] = *b"BWEA";
pub const ENTITY_AUTHORITY_SNAPSHOT_V2_TYPE_ID: &str = "blockwild.entities.authority-snapshot.r6.v2";
pub const ENTITY_AUTHORITY_SNAPSHOT_V2_OPERATION_SCHEMA: u16 = 1;
pub const ENTITY_AUTHORITY_SNAPSHOT_V2_INNER_SCHEMA: u16 = 2;

pub const ENTITY_COMPATIBILITY_RECORD_V1_MAGIC: [u8; 4] = *b"BWEC";
pub const ENTITY_COMPATIBILITY_RECORD_V1_TYPE_ID: &str = "blockwild.entities.compatibility-record.r6.v1";
pub const ENTITY_COMPATIBILITY_RECORD_V1_OPERATION_SCHEMA: u16 = 1;
pub const ENTITY_COMPATIBILITY_RECORD_V1_INNER_SCHEMA: u16 = 1;

pub const ENTITY_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWA6";
pub const ENTITY_RECEIPT_V1_TYPE_ID: &str = "blockwild.entities.event-batch.r6.v1";
pub const ENTITY_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const ENTITY_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const BASIC_DIRT_ACTION_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWQ7";
pub const BASIC_DIRT_ACTION_RECEIPT_V1_TYPE_ID: &str = "blockwild.gameplay.basic-dirt-action-receipt.r7.v1";
pub const BASIC_DIRT_ACTION_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const BASIC_DIRT_ACTION_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const CONTENT_INSTALL_PAGE_V1_MAGIC: [u8; 4] = *b"BWC7";
pub const CONTENT_INSTALL_PAGE_V1_TYPE_ID: &str = "blockwild.gameplay.content-install-page.v1";
pub const CONTENT_INSTALL_PAGE_V1_OPERATION_SCHEMA: u16 = 1;
pub const CONTENT_INSTALL_PAGE_V1_INNER_SCHEMA: u16 = 1;

pub const GAMEPLAY_ACTOR_GRANT_V1_MAGIC: [u8; 4] = *b"BWK7";
pub const GAMEPLAY_ACTOR_GRANT_V1_TYPE_ID: &str = "blockwild.gameplay.actor-grant.r7.v1";
pub const GAMEPLAY_ACTOR_GRANT_V1_OPERATION_SCHEMA: u16 = 1;
pub const GAMEPLAY_ACTOR_GRANT_V1_INNER_SCHEMA: u16 = 1;

pub const GAMEPLAY_COMMAND_V1_MAGIC: [u8; 4] = *b"BWG7";
pub const GAMEPLAY_COMMAND_V1_TYPE_ID: &str = "blockwild.gameplay.command-batch.r7.v1";
pub const GAMEPLAY_COMMAND_V1_OPERATION_SCHEMA: u16 = 1;
pub const GAMEPLAY_COMMAND_V1_INNER_SCHEMA: u16 = 1;

pub const NATIVE_BLOCK_EDIT_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWZ7";
pub const NATIVE_BLOCK_EDIT_RECEIPT_V1_TYPE_ID: &str = "blockwild.gameplay.native-block-edit-receipt.r7.v1";
pub const NATIVE_BLOCK_EDIT_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const NATIVE_BLOCK_EDIT_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const NATIVE_BLOCK_EDIT_RECEIPT_V2_MAGIC: [u8; 4] = *b"BWZ8";
pub const NATIVE_BLOCK_EDIT_RECEIPT_V2_TYPE_ID: &str = "blockwild.gameplay.native-block-edit-receipt.r7.v2";
pub const NATIVE_BLOCK_EDIT_RECEIPT_V2_OPERATION_SCHEMA: u16 = 2;
pub const NATIVE_BLOCK_EDIT_RECEIPT_V2_INNER_SCHEMA: u16 = 1;

pub const NATIVE_DROP_PICKUP_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWQ8";
pub const NATIVE_DROP_PICKUP_RECEIPT_V1_TYPE_ID: &str = "blockwild.gameplay.native-drop-pickup-receipt.r7.v1";
pub const NATIVE_DROP_PICKUP_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const NATIVE_DROP_PICKUP_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const NATIVE_PLAYER_DROP_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWQ9";
pub const NATIVE_PLAYER_DROP_RECEIPT_V1_TYPE_ID: &str = "blockwild.gameplay.native-player-drop-receipt.r7.v1";
pub const NATIVE_PLAYER_DROP_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const NATIVE_PLAYER_DROP_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const PLAYER_CREATIVE_SLOT_SET_V1_MAGIC: [u8; 4] = *b"BWF7";
pub const PLAYER_CREATIVE_SLOT_SET_V1_TYPE_ID: &str = "blockwild.gameplay.player-creative-slot-set.r7.v1";
pub const PLAYER_CREATIVE_SLOT_SET_V1_OPERATION_SCHEMA: u16 = 1;
pub const PLAYER_CREATIVE_SLOT_SET_V1_INNER_SCHEMA: u16 = 1;

pub const PLAYER_INVENTORY_IMPORT_V1_MAGIC: [u8; 4] = *b"BWP7";
pub const PLAYER_INVENTORY_IMPORT_V1_TYPE_ID: &str = "blockwild.gameplay.player-inventory-import.r7.v1";
pub const PLAYER_INVENTORY_IMPORT_V1_OPERATION_SCHEMA: u16 = 1;
pub const PLAYER_INVENTORY_IMPORT_V1_INNER_SCHEMA: u16 = 1;

pub const PLAYER_LOCATOR_ITEM_CONSUME_V1_MAGIC: [u8; 4] = *b"BWV7";
pub const PLAYER_LOCATOR_ITEM_CONSUME_V1_TYPE_ID: &str = "blockwild.gameplay.player-locator-item-consume.r7.v1";
pub const PLAYER_LOCATOR_ITEM_CONSUME_V1_OPERATION_SCHEMA: u16 = 1;
pub const PLAYER_LOCATOR_ITEM_CONSUME_V1_INNER_SCHEMA: u16 = 1;

pub const BASIC_DIRT_ACTION_PROJECTION_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWR7";
pub const BASIC_DIRT_ACTION_PROJECTION_RECEIPT_V1_TYPE_ID: &str =
    "blockwild.gameplay.basic-dirt-action-projection-receipt.r7.v1";
pub const BASIC_DIRT_ACTION_PROJECTION_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const BASIC_DIRT_ACTION_PROJECTION_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const CONTENT_INSTALL_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWT7";
pub const CONTENT_INSTALL_RECEIPT_V1_TYPE_ID: &str = "blockwild.gameplay.content-install-receipt.v1";
pub const CONTENT_INSTALL_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const CONTENT_INSTALL_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const GAMEPLAY_ACTOR_GRANT_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWK7";
pub const GAMEPLAY_ACTOR_GRANT_RECEIPT_V1_TYPE_ID: &str = "blockwild.gameplay.actor-grant-receipt.r7.v1";
pub const GAMEPLAY_ACTOR_GRANT_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const GAMEPLAY_ACTOR_GRANT_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const GAMEPLAY_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWA7";
pub const GAMEPLAY_RECEIPT_V1_TYPE_ID: &str = "blockwild.gameplay.command-receipt.r7.v1";
pub const GAMEPLAY_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const GAMEPLAY_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const NATIVE_BLOCK_EDIT_PROJECTION_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWY7";
pub const NATIVE_BLOCK_EDIT_PROJECTION_RECEIPT_V1_TYPE_ID: &str =
    "blockwild.gameplay.native-block-edit-projection-receipt.r7.v1";
pub const NATIVE_BLOCK_EDIT_PROJECTION_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const NATIVE_BLOCK_EDIT_PROJECTION_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const NATIVE_BLOCK_EDIT_PROJECTION_RECEIPT_V2_MAGIC: [u8; 4] = *b"BWY8";
pub const NATIVE_BLOCK_EDIT_PROJECTION_RECEIPT_V2_TYPE_ID: &str =
    "blockwild.gameplay.native-block-edit-projection-receipt.r7.v2";
pub const NATIVE_BLOCK_EDIT_PROJECTION_RECEIPT_V2_OPERATION_SCHEMA: u16 = 2;
pub const NATIVE_BLOCK_EDIT_PROJECTION_RECEIPT_V2_INNER_SCHEMA: u16 = 1;

pub const NATIVE_DROP_PICKUP_PROJECTION_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWR8";
pub const NATIVE_DROP_PICKUP_PROJECTION_RECEIPT_V1_TYPE_ID: &str =
    "blockwild.gameplay.native-drop-pickup-projection-receipt.r7.v1";
pub const NATIVE_DROP_PICKUP_PROJECTION_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const NATIVE_DROP_PICKUP_PROJECTION_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const NATIVE_PLAYER_DROP_PROJECTION_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWS9";
pub const NATIVE_PLAYER_DROP_PROJECTION_RECEIPT_V1_TYPE_ID: &str =
    "blockwild.gameplay.native-player-drop-projection-receipt.r7.v1";
pub const NATIVE_PLAYER_DROP_PROJECTION_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const NATIVE_PLAYER_DROP_PROJECTION_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const PLAYER_CREATIVE_SLOT_SET_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWH7";
pub const PLAYER_CREATIVE_SLOT_SET_RECEIPT_V1_TYPE_ID: &str =
    "blockwild.gameplay.player-creative-slot-set-receipt.r7.v1";
pub const PLAYER_CREATIVE_SLOT_SET_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const PLAYER_CREATIVE_SLOT_SET_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const PLAYER_INVENTORY_IMPORT_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWI7";
pub const PLAYER_INVENTORY_IMPORT_RECEIPT_V1_TYPE_ID: &str = "blockwild.gameplay.player-inventory-import-receipt.r7.v1";
pub const PLAYER_INVENTORY_IMPORT_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const PLAYER_INVENTORY_IMPORT_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const PLAYER_LOCATOR_ITEM_CONSUME_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWX7";
pub const PLAYER_LOCATOR_ITEM_CONSUME_RECEIPT_V1_TYPE_ID: &str =
    "blockwild.gameplay.player-locator-item-consume-receipt.r7.v1";
pub const PLAYER_LOCATOR_ITEM_CONSUME_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const PLAYER_LOCATOR_ITEM_CONSUME_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const PERSISTENCE_DISPATCH_V1_MAGIC: [u8; 4] = *b"BWD8";
pub const PERSISTENCE_DISPATCH_V1_TYPE_ID: &str = "blockwild.persistence.dispatch.r8.v1";
pub const PERSISTENCE_DISPATCH_V1_OPERATION_SCHEMA: u16 = 1;
pub const PERSISTENCE_DISPATCH_V1_INNER_SCHEMA: u16 = 1;

pub const PERSISTENCE_DISPATCH_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWA8";
pub const PERSISTENCE_DISPATCH_RECEIPT_V1_TYPE_ID: &str = "blockwild.persistence.dispatch-receipt.r8.v1";
pub const PERSISTENCE_DISPATCH_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const PERSISTENCE_DISPATCH_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_AGENT_GRANT_V1_MAGIC: [u8; 4] = *b"BWJ9";
pub const NETWORK_AGENT_GRANT_V1_TYPE_ID: &str = "blockwild.network.agent-grant.install.v1";
pub const NETWORK_AGENT_GRANT_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_AGENT_GRANT_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_COMMAND_RELEASE_V1_MAGIC: [u8; 4] = *b"BWM9";
pub const NETWORK_COMMAND_RELEASE_V1_TYPE_ID: &str = "blockwild.network.command.release.v1";
pub const NETWORK_COMMAND_RELEASE_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_COMMAND_RELEASE_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_DELTA_BUILD_V1_MAGIC: [u8; 4] = *b"BWD9";
pub const NETWORK_DELTA_BUILD_V1_TYPE_ID: &str = "blockwild.network.delta.build.v1";
pub const NETWORK_DELTA_BUILD_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_DELTA_BUILD_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_PEER_GRANT_V1_MAGIC: [u8; 4] = *b"BWP9";
pub const NETWORK_PEER_GRANT_V1_TYPE_ID: &str = "blockwild.network.peer-grant.install.v1";
pub const NETWORK_PEER_GRANT_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_PEER_GRANT_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_PEER_RELEASE_V1_MAGIC: [u8; 4] = *b"BWL9";
pub const NETWORK_PEER_RELEASE_V1_TYPE_ID: &str = "blockwild.network.peer.release.v1";
pub const NETWORK_PEER_RELEASE_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_PEER_RELEASE_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_RECONNECT_V1_MAGIC: [u8; 4] = *b"BWC9";
pub const NETWORK_RECONNECT_V1_TYPE_ID: &str = "blockwild.network.reconnect-checkpoint.read.v1";
pub const NETWORK_RECONNECT_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_RECONNECT_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_REPLICATION_REMOVE_V1_MAGIC: [u8; 4] = *b"BWI9";
pub const NETWORK_REPLICATION_REMOVE_V1_TYPE_ID: &str = "blockwild.network.replication-record.remove.v1";
pub const NETWORK_REPLICATION_REMOVE_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_REPLICATION_REMOVE_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_REPLICATION_UPSERT_V1_MAGIC: [u8; 4] = *b"BWI9";
pub const NETWORK_REPLICATION_UPSERT_V1_TYPE_ID: &str = "blockwild.network.replication-record.upsert.v1";
pub const NETWORK_REPLICATION_UPSERT_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_REPLICATION_UPSERT_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_BROWSER_REQUEST_V1_MAGIC: [u8; 4] = *b"BWRN";
pub const NETWORK_BROWSER_REQUEST_V1_TYPE_ID: &str = "blockwild.network.browser-request.r9.v1";
pub const NETWORK_BROWSER_REQUEST_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_BROWSER_REQUEST_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_AGENT_GRANT_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWJ9";
pub const NETWORK_AGENT_GRANT_RECEIPT_V1_TYPE_ID: &str = "blockwild.network.grant-install-receipt.v1";
pub const NETWORK_AGENT_GRANT_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_AGENT_GRANT_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_COMMAND_RELEASE_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWM9";
pub const NETWORK_COMMAND_RELEASE_RECEIPT_V1_TYPE_ID: &str = "blockwild.network.command.release-receipt.v1";
pub const NETWORK_COMMAND_RELEASE_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_COMMAND_RELEASE_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_DELTA_BUILD_RESPONSE_V1_MAGIC: [u8; 4] = *b"BWH9";
pub const NETWORK_DELTA_BUILD_RESPONSE_V1_TYPE_ID: &str = "blockwild.network.delta.build-response.v1";
pub const NETWORK_DELTA_BUILD_RESPONSE_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_DELTA_BUILD_RESPONSE_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_PEER_GRANT_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWP9";
pub const NETWORK_PEER_GRANT_RECEIPT_V1_TYPE_ID: &str = "blockwild.network.grant-install-receipt.v1";
pub const NETWORK_PEER_GRANT_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_PEER_GRANT_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_PEER_RELEASE_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWL9";
pub const NETWORK_PEER_RELEASE_RECEIPT_V1_TYPE_ID: &str = "blockwild.network.peer.release-receipt.v1";
pub const NETWORK_PEER_RELEASE_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_PEER_RELEASE_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_RECONNECT_RESPONSE_V1_MAGIC: [u8; 4] = *b"BWC9";
pub const NETWORK_RECONNECT_RESPONSE_V1_TYPE_ID: &str = "blockwild.network.reconnect-checkpoint.response.v1";
pub const NETWORK_RECONNECT_RESPONSE_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_RECONNECT_RESPONSE_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_REPLICATION_REMOVE_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWR9";
pub const NETWORK_REPLICATION_REMOVE_RECEIPT_V1_TYPE_ID: &str = "blockwild.network.replication-record-receipt.v1";
pub const NETWORK_REPLICATION_REMOVE_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_REPLICATION_REMOVE_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_REPLICATION_UPSERT_RECEIPT_V1_MAGIC: [u8; 4] = *b"BWI9";
pub const NETWORK_REPLICATION_UPSERT_RECEIPT_V1_TYPE_ID: &str = "blockwild.network.replication-record-receipt.v1";
pub const NETWORK_REPLICATION_UPSERT_RECEIPT_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_REPLICATION_UPSERT_RECEIPT_V1_INNER_SCHEMA: u16 = 1;

pub const NETWORK_BROWSER_RESPONSE_V1_MAGIC: [u8; 4] = *b"BWNA";
pub const NETWORK_BROWSER_RESPONSE_V1_TYPE_ID: &str = "blockwild.network.browser-response.r9.v1";
pub const NETWORK_BROWSER_RESPONSE_V1_OPERATION_SCHEMA: u16 = 1;
pub const NETWORK_BROWSER_RESPONSE_V1_INNER_SCHEMA: u16 = 1;

pub const INTEGRATED_RUNTIME_DOMAIN_WIRE_FAMILIES_V1: &[IntegratedRuntimeDomainWireFamilyV1] = &[
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "context-command-continuity-v2",
        direction: "request",
        magic: *b"BWS6",
        type_id: "blockwild.simulation.context-command-continuity.r5.v2",
        operation_schema: 2,
        inner_schema: 2,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "player-bootstrap-status-v1",
        direction: "request",
        magic: *b"BWS5",
        type_id: "blockwild.simulation.player-bootstrap-status.r5.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "player-combat-bootstrap-status-v1",
        direction: "request",
        magic: *b"BWS7",
        type_id: "blockwild.simulation.player-combat-bootstrap-status.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "player-game-mode-set-v1",
        direction: "request",
        magic: *b"BWM7",
        type_id: "blockwild.simulation.player-game-mode-set.r5.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "player-respawn-v1",
        direction: "request",
        magic: *b"BWD7",
        type_id: "blockwild.simulation.player-respawn.r5-r6-r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "simulation-camera-config-v1",
        direction: "request",
        magic: *b"BWC5",
        type_id: "blockwild.simulation.camera-config.r5.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "simulation-player-bind-v2",
        direction: "request",
        magic: *b"BWB6",
        type_id: "blockwild.simulation.player-bind.r5.v2",
        operation_schema: 2,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "simulation-player-bind-v3",
        direction: "request",
        magic: *b"BWB6",
        type_id: "blockwild.simulation.player-bind.r5.v3",
        operation_schema: 3,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "simulation-player-bind-v4",
        direction: "request",
        magic: *b"BWB6",
        type_id: "blockwild.simulation.player-bind.r5.v4",
        operation_schema: 4,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "context-command-continuity-receipt-v2",
        direction: "receipt",
        magic: *b"BWO6",
        type_id: "blockwild.simulation.context-command-continuity-receipt.r5.v2",
        operation_schema: 2,
        inner_schema: 2,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "player-bootstrap-status-receipt-v1",
        direction: "receipt",
        magic: *b"BWO5",
        type_id: "blockwild.simulation.player-bootstrap-status-receipt.r5.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "player-combat-bootstrap-status-receipt-v1",
        direction: "receipt",
        magic: *b"BWO7",
        type_id: "blockwild.simulation.player-combat-bootstrap-status-receipt.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "player-game-mode-set-receipt-v1",
        direction: "receipt",
        magic: *b"BWN7",
        type_id: "blockwild.simulation.player-game-mode-set-receipt.r5.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "player-respawn-receipt-v1",
        direction: "receipt",
        magic: *b"BWE7",
        type_id: "blockwild.simulation.player-respawn-receipt.r5-r6-r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "simulation-camera-config-receipt-v1",
        direction: "receipt",
        magic: *b"BWR5",
        type_id: "blockwild.simulation.camera-config-receipt.r5.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "simulation-player-bind-receipt-v2",
        direction: "receipt",
        magic: *b"BWB6",
        type_id: "blockwild.simulation.player-bind-receipt.r5.v2",
        operation_schema: 2,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "simulation-player-bind-final-receipt-v3",
        direction: "receipt",
        magic: *b"BWF6",
        type_id: "blockwild.simulation.player-bind-final-receipt.r5.v3",
        operation_schema: 3,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R5",
        domain: "simulation",
        id: "simulation-player-bind-final-receipt-v4",
        direction: "receipt",
        magic: *b"BWF7",
        type_id: "blockwild.simulation.player-bind-final-receipt.r5.v4",
        operation_schema: 4,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R6",
        domain: "entities",
        id: "entity-authority-export-v1",
        direction: "request",
        magic: *b"BWQ6",
        type_id: "blockwild.entities.authority-export.r6.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R6",
        domain: "entities",
        id: "entity-authority-import-v2",
        direction: "request",
        magic: *b"BWI6",
        type_id: "blockwild.entities.authority-import.r6.v2",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R6",
        domain: "entities",
        id: "entity-compatibility-export-v1",
        direction: "request",
        magic: *b"BWQ5",
        type_id: "blockwild.entities.compatibility-export.r6.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R6",
        domain: "entities",
        id: "entity-compatibility-import-v1",
        direction: "request",
        magic: *b"BWI5",
        type_id: "blockwild.entities.compatibility-import.r6.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R6",
        domain: "entities",
        id: "entity-command-v1",
        direction: "request",
        magic: *b"BWE6",
        type_id: "blockwild.entities.command-batch.r6.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R6",
        domain: "entities",
        id: "entity-authority-import-receipt-v1",
        direction: "receipt",
        magic: *b"BWU6",
        type_id: "blockwild.entities.authority-import-receipt.r6.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R6",
        domain: "entities",
        id: "entity-authority-snapshot-v2",
        direction: "receipt",
        magic: *b"BWEA",
        type_id: "blockwild.entities.authority-snapshot.r6.v2",
        operation_schema: 1,
        inner_schema: 2,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R6",
        domain: "entities",
        id: "entity-compatibility-record-v1",
        direction: "receipt",
        magic: *b"BWEC",
        type_id: "blockwild.entities.compatibility-record.r6.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R6",
        domain: "entities",
        id: "entity-receipt-v1",
        direction: "receipt",
        magic: *b"BWA6",
        type_id: "blockwild.entities.event-batch.r6.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "basic-dirt-action-receipt-v1",
        direction: "request",
        magic: *b"BWQ7",
        type_id: "blockwild.gameplay.basic-dirt-action-receipt.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "content-install-page-v1",
        direction: "request",
        magic: *b"BWC7",
        type_id: "blockwild.gameplay.content-install-page.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "gameplay-actor-grant-v1",
        direction: "request",
        magic: *b"BWK7",
        type_id: "blockwild.gameplay.actor-grant.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "gameplay-command-v1",
        direction: "request",
        magic: *b"BWG7",
        type_id: "blockwild.gameplay.command-batch.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "native-block-edit-receipt-v1",
        direction: "request",
        magic: *b"BWZ7",
        type_id: "blockwild.gameplay.native-block-edit-receipt.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "native-block-edit-receipt-v2",
        direction: "request",
        magic: *b"BWZ8",
        type_id: "blockwild.gameplay.native-block-edit-receipt.r7.v2",
        operation_schema: 2,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "native-drop-pickup-receipt-v1",
        direction: "request",
        magic: *b"BWQ8",
        type_id: "blockwild.gameplay.native-drop-pickup-receipt.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "native-player-drop-receipt-v1",
        direction: "request",
        magic: *b"BWQ9",
        type_id: "blockwild.gameplay.native-player-drop-receipt.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "player-creative-slot-set-v1",
        direction: "request",
        magic: *b"BWF7",
        type_id: "blockwild.gameplay.player-creative-slot-set.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "player-inventory-import-v1",
        direction: "request",
        magic: *b"BWP7",
        type_id: "blockwild.gameplay.player-inventory-import.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "player-locator-item-consume-v1",
        direction: "request",
        magic: *b"BWV7",
        type_id: "blockwild.gameplay.player-locator-item-consume.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "basic-dirt-action-projection-receipt-v1",
        direction: "receipt",
        magic: *b"BWR7",
        type_id: "blockwild.gameplay.basic-dirt-action-projection-receipt.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "content-install-receipt-v1",
        direction: "receipt",
        magic: *b"BWT7",
        type_id: "blockwild.gameplay.content-install-receipt.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "gameplay-actor-grant-receipt-v1",
        direction: "receipt",
        magic: *b"BWK7",
        type_id: "blockwild.gameplay.actor-grant-receipt.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "gameplay-receipt-v1",
        direction: "receipt",
        magic: *b"BWA7",
        type_id: "blockwild.gameplay.command-receipt.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "native-block-edit-projection-receipt-v1",
        direction: "receipt",
        magic: *b"BWY7",
        type_id: "blockwild.gameplay.native-block-edit-projection-receipt.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "native-block-edit-projection-receipt-v2",
        direction: "receipt",
        magic: *b"BWY8",
        type_id: "blockwild.gameplay.native-block-edit-projection-receipt.r7.v2",
        operation_schema: 2,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "native-drop-pickup-projection-receipt-v1",
        direction: "receipt",
        magic: *b"BWR8",
        type_id: "blockwild.gameplay.native-drop-pickup-projection-receipt.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "native-player-drop-projection-receipt-v1",
        direction: "receipt",
        magic: *b"BWS9",
        type_id: "blockwild.gameplay.native-player-drop-projection-receipt.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "player-creative-slot-set-receipt-v1",
        direction: "receipt",
        magic: *b"BWH7",
        type_id: "blockwild.gameplay.player-creative-slot-set-receipt.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "player-inventory-import-receipt-v1",
        direction: "receipt",
        magic: *b"BWI7",
        type_id: "blockwild.gameplay.player-inventory-import-receipt.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R7",
        domain: "gameplay",
        id: "player-locator-item-consume-receipt-v1",
        direction: "receipt",
        magic: *b"BWX7",
        type_id: "blockwild.gameplay.player-locator-item-consume-receipt.r7.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R8",
        domain: "persistence",
        id: "persistence-dispatch-v1",
        direction: "request",
        magic: *b"BWD8",
        type_id: "blockwild.persistence.dispatch.r8.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R8",
        domain: "persistence",
        id: "persistence-dispatch-receipt-v1",
        direction: "receipt",
        magic: *b"BWA8",
        type_id: "blockwild.persistence.dispatch-receipt.r8.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-agent-grant-v1",
        direction: "request",
        magic: *b"BWJ9",
        type_id: "blockwild.network.agent-grant.install.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-command-release-v1",
        direction: "request",
        magic: *b"BWM9",
        type_id: "blockwild.network.command.release.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-delta-build-v1",
        direction: "request",
        magic: *b"BWD9",
        type_id: "blockwild.network.delta.build.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-peer-grant-v1",
        direction: "request",
        magic: *b"BWP9",
        type_id: "blockwild.network.peer-grant.install.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-peer-release-v1",
        direction: "request",
        magic: *b"BWL9",
        type_id: "blockwild.network.peer.release.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-reconnect-v1",
        direction: "request",
        magic: *b"BWC9",
        type_id: "blockwild.network.reconnect-checkpoint.read.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-replication-remove-v1",
        direction: "request",
        magic: *b"BWI9",
        type_id: "blockwild.network.replication-record.remove.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-replication-upsert-v1",
        direction: "request",
        magic: *b"BWI9",
        type_id: "blockwild.network.replication-record.upsert.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-browser-request-v1",
        direction: "request",
        magic: *b"BWRN",
        type_id: "blockwild.network.browser-request.r9.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-agent-grant-receipt-v1",
        direction: "receipt",
        magic: *b"BWJ9",
        type_id: "blockwild.network.grant-install-receipt.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-command-release-receipt-v1",
        direction: "receipt",
        magic: *b"BWM9",
        type_id: "blockwild.network.command.release-receipt.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-delta-build-response-v1",
        direction: "receipt",
        magic: *b"BWH9",
        type_id: "blockwild.network.delta.build-response.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-peer-grant-receipt-v1",
        direction: "receipt",
        magic: *b"BWP9",
        type_id: "blockwild.network.grant-install-receipt.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-peer-release-receipt-v1",
        direction: "receipt",
        magic: *b"BWL9",
        type_id: "blockwild.network.peer.release-receipt.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-reconnect-response-v1",
        direction: "receipt",
        magic: *b"BWC9",
        type_id: "blockwild.network.reconnect-checkpoint.response.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-replication-remove-receipt-v1",
        direction: "receipt",
        magic: *b"BWR9",
        type_id: "blockwild.network.replication-record-receipt.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-replication-upsert-receipt-v1",
        direction: "receipt",
        magic: *b"BWI9",
        type_id: "blockwild.network.replication-record-receipt.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
    IntegratedRuntimeDomainWireFamilyV1 {
        phase: "R9",
        domain: "network",
        id: "network-browser-response-v1",
        direction: "receipt",
        magic: *b"BWNA",
        type_id: "blockwild.network.browser-response.r9.v1",
        operation_schema: 1,
        inner_schema: 1,
        normal_path: true,
    },
];

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;

    #[test]
    fn generated_registry_is_closed_unique_and_normal_path_explicit() {
        let mut ids = BTreeSet::new();
        let mut domains = BTreeSet::new();
        for family in INTEGRATED_RUNTIME_DOMAIN_WIRE_FAMILIES_V1 {
            assert!(ids.insert(family.id), "duplicate generated family {}", family.id);
            domains.insert((family.phase, family.domain));
            assert_eq!(family.magic.len(), 4);
            assert!(family.type_id.starts_with("blockwild."));
            assert!(family.operation_schema > 0);
            assert!(family.inner_schema > 0);
        }
        assert_eq!(
            domains,
            BTreeSet::from([
                ("R5", "simulation"),
                ("R6", "entities"),
                ("R7", "gameplay"),
                ("R8", "persistence"),
                ("R9", "network"),
            ])
        );
    }
}
